FROM python:3.11-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Optional: ensure logs show immediately
ENV PYTHONUNBUFFERED=1

# Default command to run the consumer
CMD ["python", "manage.py", "start_email_consumer"]
