# Generated by Django 5.2.8 on 2025-11-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('template_code', models.CharField(max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_logs',
                'indexes': [models.Index(fields=['request_id'], name='email_logs_request_96115c_idx'), models.Index(fields=['user_id'], name='email_logs_user_id_185b75_idx'), models.Index(fields=['status'], name='email_logs_status_e3be55_idx'), models.Index(fields=['created_at'], name='email_logs_created_76afc3_idx')],
            },
        ),
    ]
